import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
    title: 'Privacy Policy | LS Connect — 3R Creative',
    description:
        'LS Connect Privacy Policy. Learn how 3R Creative (F.Z.E.) collects, uses, and protects your personal data on the WhatsApp business messaging platform.',
};

const sections = [
    { id: 'intro', label: 'Introduction' },
    { id: 'definitions', label: '1. Definitions' },
    { id: 'collection', label: '2. Information Collection' },
    { id: 'cookies', label: '3. Tracking & Cookies' },
    { id: 'use', label: '4. Use of Data' },
    { id: 'legal-basis', label: '5. Legal Basis' },
    { id: 'retention', label: '6. Retention & Transfer' },
    { id: 'disclosure', label: '7. Disclosure' },
    { id: 'rights', label: '8. Your Rights' },
    { id: 'security', label: '9. Security' },
    { id: 'children', label: '10. Children\'s Privacy' },
    { id: 'contact', label: '11. Contact' },
];

const definitions = [
    {
        term: 'Service',
        definition:
            'The LS Connect website and mobile application operated by 3R Creative (F.Z.E).',
    },
    {
        term: 'Personal Data',
        definition: 'Data about a living individual who can be identified from that data.',
    },
    {
        term: 'Usage Data',
        definition:
            'Data collected automatically, generated by the use of the Service (e.g., duration of page visit).',
    },
    {
        term: 'Data Controller',
        definition:
            'The natural or legal person who determines the purposes and manner of processing. For this Policy, we are the Data Controller.',
    },
    {
        term: 'Data Processor',
        definition: 'Any person who processes data on behalf of the Data Controller.',
    },
];

const personalDataItems = [
    'Email address',
    'First name and last name',
    'Phone number associated with WhatsApp',
    'Address, State, Province, ZIP/Postal code, City',
    'Social media login credentials (if connected)',
    'Cookies and Usage Data',
];

const cookieTypes = [
    {
        term: 'Session Cookies',
        definition: 'To operate our Service.',
    },
    {
        term: 'Preference Cookies',
        definition: 'To remember your settings.',
    },
    {
        term: 'Security Cookies',
        definition: 'For security purposes.',
    },
];

const useOfDataItems = [
    'To provide and maintain the Service',
    'To connect WhatsApp Business Accounts through Meta\u2019s embedded signup flow',
    'To manage inbox, messaging, template, and analytics features',
    'To provide customer support and monitor usage',
    'To detect, prevent, and address technical issues or fraud',
];

const legalBasisItems = [
    'You have given us consent',
    'We need to perform a contract with you',
    'The processing is in our legitimate interests',
    'To comply with legal obligations',
];

const rightsItems = [
    'The right to access, update, or delete the information we hold about you',
    'The right to rectification and to object to processing',
    'The right to data portability and to withdraw consent',
];

export default function LSConnectPrivacyPolicyPage() {
    return (
        <main className="min-h-screen bg-[#111111] text-white pt-24">
            {/* Hero */}
            <div className="px-6 py-16 md:py-20 relative overflow-hidden">
                <div
                    className="pointer-events-none absolute inset-0 opacity-100"
                    style={{
                        background:
                            'radial-gradient(ellipse 80% 55% at 50% -5%, rgba(233,195,105,0.09) 0%, transparent 70%)',
                    }}
                />
                <div
                    className="pointer-events-none absolute inset-0 opacity-[0.025]"
                    style={{
                        backgroundImage:
                            'repeating-linear-gradient(0deg,transparent,transparent 40px,#fff 40px,#fff 41px),repeating-linear-gradient(90deg,transparent,transparent 40px,#fff 40px,#fff 41px)',
                    }}
                />
                <div className="max-w-5xl mx-auto relative z-10">
                    <Link
                        href="/ls-connect"
                        className="inline-flex items-center gap-1.5 text-sm text-white/40 hover:text-[#E9C369] transition-colors mb-8"
                    >
                        <span aria-hidden="true">←</span> Back to LS Connect
                    </Link>
                    <p className="text-xs tracking-[0.3em] uppercase text-[#E9C369] mb-4">
                        LS Connect · Legal
                    </p>
                    <h1 className="text-4xl md:text-6xl font-bold leading-[1.05] tracking-tight mb-4">
                        Privacy
                        <br />
                        <span className="text-[#E9C369]">Policy</span>
                    </h1>
                    <div className="flex flex-wrap gap-6 text-sm text-white/60">
                        <span>
                            <span className="text-[#E9C369] mr-1">Platform:</span>
                            LS Connect
                        </span>
                        <span>
                            <span className="text-[#E9C369] mr-1">Company:</span>
                            3R Creative (F.Z.E.)
                        </span>
                        <span>
                            <span className="text-[#E9C369] mr-1">Last Updated:</span>
                            19 March 2026
                        </span>
                    </div>
                </div>
            </div>

            <div className="max-w-5xl mx-auto px-6 pb-20 flex flex-col lg:flex-row gap-16">
                <aside className="hidden lg:block w-56 shrink-0">
                    <div className="sticky top-28">
                        <p className="text-[10px] tracking-[0.25em] uppercase text-white/35 mb-4">
                            Contents
                        </p>
                        <nav className="flex flex-col gap-1" aria-label="Table of contents">
                            {sections.map((s) => (
                                <a
                                    key={s.id}
                                    href={`#${s.id}`}
                                    className="text-left text-sm py-1.5 px-3 rounded transition-all border-l-2 border-transparent text-white/60 hover:text-[#E9C369] hover:border-[#E9C369]"
                                >
                                    {s.label}
                                </a>
                            ))}
                        </nav>
                    </div>
                </aside>

                <article className="flex-1 min-w-0 space-y-14 text-white/85">
                    {/* Introduction */}
                    <section id="intro" className="scroll-mt-28">
                        <Prose>
                            <p>
                                <strong className="text-white">LS Connect</strong> (hereinafter referred
                                to as the &ldquo;Platform&rdquo;, &ldquo;Website&rdquo;, &ldquo;App&rdquo;,
                                or &ldquo;LS Connect&rdquo;) is a website and mobile-based client
                                communication and WhatsApp business messaging platform managed and
                                operated by <strong className="text-white">3R Creative (F.Z.E)</strong>{' '}
                                (hereinafter referred to as &ldquo;LS Connect&rdquo;, &ldquo;we&rdquo;,
                                &ldquo;us&rdquo;, or &ldquo;our&rdquo;).
                            </p>
                            <p>
                                This Privacy Policy helps you understand the type of information
                                collected, the purpose for which it is collected, how it is used, and
                                how it is protected. We take the protection of your information seriously
                                and are committed to protecting the information in our possession.
                            </p>
                            <p>
                                This Policy is published in accordance with applicable data protection
                                and privacy laws, including the laws of the United Arab Emirates and
                                other applicable international regulations such as GDPR.
                            </p>
                        </Prose>
                    </section>

                    <Divider />

                    {/* 1. Definitions */}
                    <section id="definitions" className="scroll-mt-28">
                        <SectionNumber>1</SectionNumber>
                        <SectionHeading>Definitions</SectionHeading>
                        <dl className="space-y-4">
                            {definitions.map((item) => (
                                <div
                                    key={item.term}
                                    className="border border-white/10 rounded-xl p-5 bg-[#1a1a1a]"
                                >
                                    <dt className="text-sm font-semibold text-[#E9C369] mb-1">
                                        {item.term}
                                    </dt>
                                    <dd className="text-white/60 text-[0.97rem] leading-relaxed">
                                        {item.definition}
                                    </dd>
                                </div>
                            ))}
                        </dl>
                    </section>

                    <Divider />

                    {/* 2. Information Collection */}
                    <section id="collection" className="scroll-mt-28">
                        <SectionNumber>2</SectionNumber>
                        <SectionHeading>Information Collection and Use</SectionHeading>
                        <Prose>
                            <p>
                                We collect several different types of information for various purposes
                                to provide and improve our Service to you.
                            </p>
                        </Prose>

                        <SubHeading>2.1 Personal Data</SubHeading>
                        <Prose>
                            <p>
                                While using our Service, we may ask you to provide certain personally
                                identifiable information, including but not limited to:
                            </p>
                        </Prose>
                        <List items={personalDataItems} />

                        <SubHeading>2.2 Usage Data</SubHeading>
                        <Prose>
                            <p>
                                We may collect information that your browser sends whenever you visit
                                our Service, such as your IP address, browser type, pages visited, time
                                spent, and unique device identifiers.
                            </p>
                        </Prose>

                        <SubHeading>2.3 Behavioral and Location Data</SubHeading>
                        <Prose>
                            <p>
                                We collect information related to your activity on the Platform (feature
                                use, template management, etc.) and general location information derived
                                from your IP address for security and analytics purposes.
                            </p>
                        </Prose>

                        <SubHeading>2.4 Contact List &amp; Files</SubHeading>
                        <Prose>
                            <p>
                                We allow you to upload or import your existing contact list and files
                                (images, audio, video, documents) in connection with messaging and
                                customer support features.
                            </p>
                        </Prose>
                    </section>

                    <Divider />

                    {/* 3. Cookies */}
                    <section id="cookies" className="scroll-mt-28">
                        <SectionNumber>3</SectionNumber>
                        <SectionHeading>Tracking &amp; Cookies Data</SectionHeading>
                        <Prose>
                            <p>
                                We use cookies and similar tracking technologies to track activity on
                                our Service and hold certain information. Examples include:
                            </p>
                        </Prose>
                        <dl className="mt-4 space-y-3">
                            {cookieTypes.map((item) => (
                                <div key={item.term} className="flex gap-3 text-[0.97rem] leading-relaxed">
                                    <span className="mt-[0.4rem] shrink-0 w-1.5 h-1.5 rounded-full bg-[#E9C369]" />
                                    <p className="text-white/60">
                                        <strong className="text-white">{item.term}:</strong>{' '}
                                        {item.definition}
                                    </p>
                                </div>
                            ))}
                        </dl>
                    </section>

                    <Divider />

                    {/* 4. Use of Data */}
                    <section id="use" className="scroll-mt-28">
                        <SectionNumber>4</SectionNumber>
                        <SectionHeading>Use of Data</SectionHeading>
                        <Prose>
                            <p>3R Creative (F.Z.E) uses the collected data for the following purposes:</p>
                        </Prose>
                        <List items={useOfDataItems} />
                    </section>

                    <Divider />

                    {/* 5. Legal Basis */}
                    <section id="legal-basis" className="scroll-mt-28">
                        <SectionNumber>5</SectionNumber>
                        <SectionHeading>Legal Basis for Processing</SectionHeading>
                        <Prose>
                            <p>We process your Personal Data because:</p>
                        </Prose>
                        <List items={legalBasisItems} />
                    </section>

                    <Divider />

                    {/* 6. Retention */}
                    <section id="retention" className="scroll-mt-28">
                        <SectionNumber>6</SectionNumber>
                        <SectionHeading>Retention and Transfer of Data</SectionHeading>
                        <Prose>
                            <p>
                                We will retain your Personal Data only for as long as necessary for the
                                purposes set out in this Policy. Your information may be transferred to
                                and processed in countries outside your country of residence where data
                                protection laws may differ.
                            </p>
                        </Prose>
                    </section>

                    <Divider />

                    {/* 7. Disclosure */}
                    <section id="disclosure" className="scroll-mt-28">
                        <SectionNumber>7</SectionNumber>
                        <SectionHeading>Disclosure of Data</SectionHeading>
                        <Prose>
                            <p>
                                We may disclose your data in good faith to comply with legal obligations,
                                protect the rights or property of 3R Creative (F.Z.E), prevent wrongdoing,
                                or protect the personal safety of users.
                            </p>
                        </Prose>
                    </section>

                    <Divider />

                    {/* 8. Rights */}
                    <section id="rights" className="scroll-mt-28">
                        <SectionNumber>8</SectionNumber>
                        <SectionHeading>Your Data Protection Rights</SectionHeading>
                        <Prose>
                            <p>Depending on your location, you may have the following rights:</p>
                        </Prose>
                        <List items={rightsItems} />
                        <Prose>
                            <p className="mt-4">
                                To exercise these rights, please contact us at{' '}
                                <a
                                    href="mailto:info@creative3r.com"
                                    className="text-[#E9C369] hover:underline underline-offset-4"
                                >
                                    info@creative3r.com
                                </a>
                                . You may also submit a{' '}
                                <Link
                                    href="/ls-connect/data-deletion"
                                    className="text-[#E9C369] hover:underline underline-offset-4"
                                >
                                    data deletion request
                                </Link>
                                .
                            </p>
                        </Prose>
                    </section>

                    <Divider />

                    {/* 9. Security */}
                    <section id="security" className="scroll-mt-28">
                        <SectionNumber>9</SectionNumber>
                        <SectionHeading>Security of Data</SectionHeading>
                        <Prose>
                            <p>
                                While we strive to use commercially reasonable means to protect your
                                Personal Data, no method of transmission over the Internet is 100% secure,
                                and we cannot guarantee absolute security.
                            </p>
                        </Prose>
                    </section>

                    <Divider />

                    {/* 10. Children */}
                    <section id="children" className="scroll-mt-28">
                        <SectionNumber>10</SectionNumber>
                        <SectionHeading>Children&apos;s Privacy</SectionHeading>
                        <Prose>
                            <p>
                                Our Service is not intended for individuals under the age of 18. We do
                                not knowingly collect information from anyone under 18.
                            </p>
                        </Prose>
                    </section>

                    <Divider />

                    {/* 11. Contact */}
                    <section id="contact" className="scroll-mt-28">
                        <SectionNumber>11</SectionNumber>
                        <SectionHeading>Contact Us</SectionHeading>
                        <Prose>
                            <p>
                                If you have questions about this Privacy Policy or your data, please
                                contact us at:
                            </p>
                        </Prose>
                        <div className="mt-6 grid sm:grid-cols-3 gap-4">
                            <ContactCard label="Email">
                                <a
                                    href="mailto:info@creative3r.com"
                                    className="hover:underline underline-offset-4"
                                >
                                    info@creative3r.com
                                </a>
                            </ContactCard>
                            <ContactCard label="Company">3R Creative (F.Z.E.)</ContactCard>
                            <ContactCard label="Address">
                                C1 Building, 1-F, Ajman Free Zone, Ajman, UAE
                            </ContactCard>
                        </div>
                        <p className="mt-8 text-xs text-white/35 leading-relaxed">
                            LS Connect
                            <br />
                            © 2026 3R Creative (F.Z.E.). All rights reserved.
                            <br />
                            C1 Building, 1-F, Ajman Free Zone, Ajman, UAE.
                        </p>
                    </section>

                    <div className="pt-6 border-t border-white/10">
                        <Link
                            href="/ls-connect"
                            className="text-sm text-[#E9C369] hover:underline underline-offset-4"
                        >
                            ← Return to LS Connect
                        </Link>
                    </div>
                </article>
            </div>
        </main>
    );
}

function SectionNumber({ children }: { children: React.ReactNode }) {
    return (
        <span className="text-[11px] tracking-[0.25em] uppercase text-[#E9C369] mb-1 block">
            Section {children}
        </span>
    );
}

function SectionHeading({ children }: { children: React.ReactNode }) {
    return (
        <h2 className="text-2xl md:text-3xl font-bold tracking-tight text-white mb-5 leading-snug">
            {children}
        </h2>
    );
}

function SubHeading({ children }: { children: React.ReactNode }) {
    return (
        <h3 className="text-sm font-semibold text-white mt-7 mb-2 uppercase tracking-wide">
            {children}
        </h3>
    );
}

function Prose({ children }: { children: React.ReactNode }) {
    return (
        <div className="space-y-3 text-white/70 leading-relaxed text-[0.97rem]">{children}</div>
    );
}

function List({ items }: { items: React.ReactNode[] }) {
    return (
        <ul className="mt-3 space-y-2">
            {items.map((item, i) => (
                <li key={i} className="flex gap-3 text-white/70 text-[0.97rem] leading-relaxed">
                    <span className="mt-[0.4rem] shrink-0 w-1.5 h-1.5 rounded-full bg-[#E9C369]" />
                    <span>{item}</span>
                </li>
            ))}
        </ul>
    );
}

function Divider() {
    return <hr className="border-white/10" />;
}

function ContactCard({ label, children }: { label: string; children: React.ReactNode }) {
    return (
        <div className="bg-[#E9C369]/8 border border-[#E9C369]/25 rounded-xl p-5">
            <p className="text-[10px] tracking-[0.2em] uppercase text-white/40 mb-2">{label}</p>
            <p className="text-[#E9C369] text-sm font-medium leading-relaxed">{children}</p>
        </div>
    );
}
